name: Build and Lint Android App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          # Ensure JDK is compatible with your React Native version

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Ensure Node.js is compatible with your React Native version

      - name: Install Dependencies
        run: npm install

      - name: Run Jest Tests with Coverage
        run: npx jest --coverage

      - name: Verify Node.js Version
        run: node -v # Ensures correct Node version is used

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      #- name: Lint Code
      #  run: npm run lint

      - name: Run Tests
        run: npx jest --coverage

      - name: Run SonarQube Scanner
        run: npx sonar-scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Grant Execute Permission to Gradle Wrapper
        run: chmod +x android/gradlew

      - name: Build Android APK
        run: |
          cd android 
          ./gradlew assembleRelease bundleRelease

        #./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ReactNativeAndroid
          path: |
            android/app/build/outputs/apk/release/ReactNativeAndroid.apk
