name: Build and Lint Android App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 22.13.1
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Set to your required Node.js version
          cache: 'npm'

      - name: Verify Node.js Version
        run: node -v # Ensures correct Node version is used

      - name: Install Dependencies
        run: npm ci

      #- name: Lint Code
      #  run: npm run lint

      - name: Run Tests
        run: npm run test:coverage

      - name: Run SonarQube Scanner
        run: npx sonar-scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Grant Execute Permission to Gradle Wrapper
        run: chmod +x android/gradlew

      - name: Build Android APK
        run: |
          cd android 
          ./gradlew assembleRelease bundleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ReactNativeAndroid-build
          path: |
            android/app/build/outputs/apk/release/app-release.apk
            ##./gradlew assembleDebug
